//default actions
export const FAILURE_NETWORK = 'FAILURE_NETWORK'
export const SUCCESS_NETWORK = 'SUCCESS_NETWORK'

//user actions
export const REQUEST_USER_LIST = 'REQUEST_USER_LIST'
export const SUCCESS_USER_LIST = 'SUCCESS_USER_LIST'
export const FAILURE_USER_LIST = 'FAILURE_USER_LIST'

export const REQUEST_USER_LOGIN = 'REQUEST_USER_LOGIN'
export const SUCCESS_USER_LOGIN = 'SUCCESS_USER_LOGIN'
export const FAILURE_USER_LOGIN = 'FAILURE_USER_LOGIN'

export const REQUEST_USER_CREDENTIALS = 'REQUEST_USER_CREDENTIALS'
export const SUCCESS_USER_CREDENTIALS = 'SUCCESS_USER_CREDENTIALS'
export const FAILURE_USER_CREDENTIALS = 'FAILURE_USER_CREDENTIALS'

//dashboard actions
export const REQUEST_DASHBOARD_DATA = 'REQUEST_DASHBOARD_DATA'

//customer actions
export const REQUEST_SAVE_CUSTOMER_PERSON = 'REQUEST_SAVE_CUSTOMER_PERSON'
export const REQUEST_SAVE_CUSTOMER_PERSON_SUCCESS = 'REQUEST_SAVE_CUSTOMER_PERSON_SUCCESS'
export const REQUEST_SAVE_CUSTOMER_PERSON_FAILURE = 'REQUEST_SAVE_CUSTOMER_PERSON_FAILURE'